### Get all todos
GET http://localhost:5287/todos

### Create a new todo
POST http://localhost:5287/todos
content-type: application/json

{
    "id": 2,
    "name": "Write Anotha demo",
    "dueDate": "2026-12-31",
    "isCompleted": false
}

### Request to get the todo with id #
GET http://localhost:5287/todos/1

### Delete the todo with id #
DELETE http://localhost:5287/todos/1

### Update the todo with id #
GET http://localhost:5287/tasks/1